/* This file was automatically generated by codegen and should not be edited */
import * as Types from '../../apollo/types'

export type NewBlockFeedSubscriptionVariables = Types.Exact<{
    [key: string]: never
}>

export type NewBlockFeedSubscription = {
    __typename?: 'Subscription'
    newBlockFeed: {
        __typename?: 'BlockSummary'
        number: number
        miner: string
        txCount: number
        timestamp: number
    }
}
