/* This file was automatically generated by codegen and should not be edited */
import * as Types from '../../../apollo/types'

export type GetLatestBlockInfoQueryVariables = Types.Exact<{ [key: string]: never }>

export type GetLatestBlockInfoQuery = {
    __typename?: 'Query'
    getLatestBlockInfo: { __typename?: 'LatestBlockData'; number: number; avgBlockTime: number; hashRate: string; difficulty: string }
}
