#!/bin/sh
RED='\033[0;31m'
NC='\033[0;37m' 

if ! head -1 "$1" | grep -qE "^(devop|feat|fix|ci|chore|docs|test|ui|refactor|perf|build|revert|style)(\(.+?\))?: .{1,}$"; then
    echo "${RED}COMMIT ERROR: ${NC}Your commit message is invalid. Please use git-cz command to create a commit" >&2
    exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
    echo "${RED}COMMIT ERROR: ${NC}Your commit message is too long. Please use git-cz command to create a commit" >&2
    exit 1
fi